inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "test/**/*"
    - "spec/**/*"
