inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - lib/**/*
    - tmp/**/*
    - vendor/**/*
    - log/**/*
    - node_modules/**/*
    - spec/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
