---
default: &default
  author:      'Generic Author'
  author_home: 'http://www.heroku.com/'
  twitter_id:  '@isaiaspina'
  facebk_id:   '297759137246012'
  site_url:    'reg.herokuapp.com'

  default_url: 'https://reg.herokuapp.com'
  mailer_from_addr: 'Registro <registro@google.com>'
  letsencrypt: none

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
