registration_starts:   '2017-08-20 00:00:00'
registration_deadline: '2017-11-10 00:00:00'
food_deadline:         '2017-11-10 00:00:00'
allocation_deadline:   '2017-11-10 00:00:00'
transport_deadline:    '2017-11-10 00:00:00'
event_ends:            '2017-11-20 14:00:00'
registration_deadline_show: false
event_id:              2017
adult_age:             11
event_full_price:      100
food_full_price:       60
food_half_price:       30
allocation_full_price: 100
allocation_half_price: 50
transport_full_price:  10
max_allocation_men:    125
max_allocation_women:  125
max_food:              500
max_people:            1200
main_phone_sched: 'Monday to Saturday, 9am-5pm'
main_phone:       '1234567890'
main_email:       'email@email.com'
event_name:       '4a Conferencia Anual'
event_title:      '"Antigua Doctrina, Nueva Reforma"'
event_subtitle:   '1517 - 2017'
event_dates:      'Noviembre 17-20, 2017 / Guadalajara, Jalisco, MX'
location_mapslnk: 'https://www.google.com.mx/maps/place/Instituto+Bíblico+la+Roca,+La+Roca,+Jal.,+México'                      # 'https://www.google.com.mx/maps/place/20%C2%B030\'49.4%22N+103%C2%B025\'35.8%22W/@20.513707,-103.426596,17z/data=!3m1!4b1!4m2!3m1!1s0x0:0x0?hl=es-419'
dektop_app_url:   '' #DEPRECATED
api_user:         'user'
api_pass:         'pass'
site_author:      'Custom Author'
site_home_url:    'http://www.foo.com/'
weather_url:      'https://www.wunderground.com/q/zmw:00000.24.76613'

schedule_show: true
schedule:
  friday:
    date: 2017-11-17
    day:
      '3:00pm': Registro y Convivio
      '5:30pm': Bienvenida e Himnos y Salmos
      '6:00pm': Prédica
      '7:00pm': Prédica
      '7:45pm': Anuncios
      '8:00pm': '{fa-cutlery} Cena'
  saturday:
    date: 2017-11-18
    day:
      '8:00am':  '{fa-cutlery} Desayuno'
      '9:10am': '{fa-comment} Oración en Grupos'
      '9:45am': Himnos y Salmos
      '10:10am': Prédica
      '11:15am': Prédica
      '12:15pm': Coffee Break
      '12:50pm': Prédica
      '2:00pm': '{fa-cutlery} Comida'
      '4:00pm': Himnos y Salmos
      '4:15pm': Prédica
      '5:15pm': Prédica
      '6:15pm': Coffee Break
      '6:45pm': Prédica
      '7:45pm': Anuncios
      '8:00pm': '{fa-cutlery} Cena'
  sunday:
    date: 2017-11-19
    day:
      '8:00am': '{fa-cutlery} Desayuno'
      '9:10am': '{fa-comment} Oración en Grupos'
      '9:50am': Prédica
      '11:00am': Culto
      '12:30pm': Coffee Break
      '1:00pm': Prédica
      '2:00pm': '{fa-cutlery} Comida'
      '4:00pm': Himnos y Salmos
      '4:20pm': Prédica
      '5:30pm': Prédica
      '6:30pm': Anuncios
      '6:45pm': Coffee Break y Convivio
      '8:00pm': '{fa-cutlery} Cena'
  monday:
    date: 2017-11-20
    day:
      '8:00am': '{fa-cutlery} Desayuno'
      '9:15am': '{fa-comment} Oración en Grupos e Himnos'
      '10:00am': Prédica
      '11:10am': Prédica
      '12:15pm': Cofee Break
      '12:45pm': Prédica
      '1:45pm': Despedida

transport_schedule:
  friday:
    go: 2 pm
    ret: 8 pm
  saturday:
    go: 8 am
    ret: 8 pm
  sunday:
    go: 8 am
    ret: 8 pm
  monday:
    go: 8 am
    ret: 2 pm

paycollectors:
  - name: John Doe
    phone: '1234567899'
    phone_suffix: (Cel)
    email: foo@hotmail.com
    location: Guadalajara, JAL
    church: Iglesia del Centro
  - name: Jane Doe
    phone: '1234567899'
    phone_suffix: (Home)
    phone2: '1234567899'
    phone2_suffix: (Cel)
    email: bar@hotmail.com
    location: Guadalajara, JAL
    church: Iglesia del Centro
  - name: Foo Bar
    phone: '1234567899'
    phone_suffix: (Cel)
    email: foo@gmail.com
    location: Guadalajara, JAL
    church: Iglesia del Centro
