
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: postgres
  username: postgres
  password: postgres
  host: localhost 
  port: 5432

test:
  <<: *default
  database: postgres_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
