development:
  secret_key_base: #secret_key_base
  google_key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

test:
  secret_key_base: #secret_key_base

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_key: <%= ENV["SECRET_GOOGLE_KEY"] %>
